### ISSUE TITLE
Gradle project sync failed 

### ISSUE THREAD

**Issue by kumarjitendra** [stealthcopter/AndroidNetworkTools#10]
Hello ,
As per you recommendation when i use this  
compile 'com.github.stealthcopter:AndroidNetworkTools:0.1.2' in dependencies of build.gradle  i have gradle project sync failed .
What is the possible solution to use your library please .
Thanks 
Jitendra 

![gradle project sync failed -ping](https://cloud.githubusercontent.com/assets/7716003/23668368/2047cc2e-0361-11e7-9a4c-7544d1dfef8a.PNG)

**Comment by stealthcopter** [comment]
Have you remembered to add the remote maven url?

    repositories {
        maven {
            url "https://jitpack.io"
        }
    }

If that's not the problem can you post your whole gradle file?

Thanks

**Comment by kumarjitendra** [comment]
Hi stealthcopter,
As per your suggestion i added 
repositories {
    maven {
        url "https://jitpack.io"
    }
}
it's working fine now :) Thanks a lot for your help . 
Look forward to have more interaction to solve problems together if something comes in our way :)

**Comment by stealthcopter** [comment]
no problem :)
