### ISSUE TITLE
Should prefix with this 

### ISSUE THREAD

**Issue by MBach** [stealthcopter/AndroidNetworkTools#16]
https://github.com/stealthcopter/AndroidNetworkTools/blob/6f5ab3188846c59cf224b4783952edddc9254c03/library/src/main/java/com/stealthcopter/networktools/PortScan.java#L80

I'm creating a small app in order to play with home automation (see https://github.com/MBach/home-automation) and I have some troubles when I'm using this method. I think you should prefix with ```this``` otherwise you're just clearing the argument.

If I'm using the other method with formatted ports, like "80,3000,8080,10000" it's working fine.

**Comment by stealthcopter** [comment]
@MBach awesome, thanks for spotting this! I've dropped the clear all together as it's unnecessary in that method. Will update and push out a new release shortly.

Thanks :+1:

**Comment by stealthcopter** [comment]
Fixed in 0.2.2 
https://github.com/stealthcopter/AndroidNetworkTools/releases/tag/0.2.2
