### ISSUE TITLE
Synchronously single port scan setTimeOutMillis does not work

### ISSUE THREAD

**Issue by geckogecko** [stealthcopter/AndroidNetworkTools#17]
I am trying to scan a single port synchronously with: 
```
ArrayList<Integer> openPorts = PortScan
                        .onAddress("address")
                        .setTimeOutMillis(1000)
                        .setPort(4000)
                        .doScan();
```

If the port to scan is closed/down this call hangs for multiple minutes and does not time out after 1000ms like expected. 

Version: 0.2.1

**Comment by stealthcopter** [comment]
Awesome work, just merged it in. Thanks @geckogecko
