### ISSUE TITLE
Subnet tools (find devices on local network)

### ISSUE THREAD

**Issue by Alamusitl** [stealthcopter/AndroidNetworkTools#19]
Hi , my question is how to find devices on local network? Use the ping or have other way?

**Comment by stealthcopter** [comment]
Hi @Alamusitl Yes, currently you'd need to implement it yourself by looping over all valid addresses in the subnet and pinging to see if they are reachable. 
I will have a look at adding FindSubnetDevices as a enhancement shortly

**Comment by stealthcopter** [comment]
I've added finding subnet devices to version 0.3.0 and published a release. Enjoy :)
