### ISSUE TITLE
why the library ignore my setTimeOutMillis value?

### ISSUE THREAD

**Issue by alfo888** [stealthcopter/AndroidNetworkTools#22]
Hello, I set the setTimeOutMillis but the library seems to ignore my short value.      

PortScan.onAddress(ipAddress).setTimeOutMillis(100).setPort(Integer.valueOf(editPortNumberString)).doScan(new PortScan.PortListener() { ...

**Comment by stealthcopter** [comment]
@alfo888 This was a bug and has been fixed in the latest release, please upgrade to use 0.3.0

**Comment by alfo888** [comment]
Thanks a lot. I updated the library to version 0.3.0 and it works.
