### ISSUE TITLE
Latest APK broken

### ISSUE THREAD

**Issue by IzzySoft** [stealthcopter/AndroidNetworkTools#26]
Package Metadata are broken for the latest release:

```
CRITICAL: Failed to get apk signature
ERROR: Package matching failed: invalid literal for int() with base 10: ''
INFO: Line was: package: name='com.stealthcotper.networktools' versionCode='' versionName='' platformBuildVersionName=''
```

Could you please check and fix? `versionCode` as well as  `versionName` are empty.

**Comment by stealthcopter** [comment]
Ah crap. Thanks for spotting this, I'm surprised it compiled and created an apk with that error. Just pushing a new release out now.

**Comment by IzzySoft** [comment]
I was wondering the same :wink: Thanks for the fast fix! Worked out fine, fdroidserver accepted it – [update pushed out](https://apt.izzysoft.de/fdroid/index/apk/com.stealthcotper.networktools)!

**Comment by IzzySoft** [comment]
Same thing again with v0.4.0:

```
WARNING: repo/com.hdeva.launcher_1.1.6.apk is set to android:debuggable="true"
CRITICAL: Package matching failed: invalid literal for int() with base 10: ''
Line was: package: name='com.stealthcotper.networktools' versionCode='' versionName='' platformBuildVersionName=''
```

Could you apply the same fix again, please?

**Comment by stealthcopter** [comment]
Omg, cant believe that happened again. Sorry. Have uploaded a new APK, should be working now :)

**Comment by IzzySoft** [comment]
Thanks a lot, Matthew – and I felt the same :wink: New APK is fine now, update just gets synced to my repo.

As you now closed the issue I cannot reopen it. Let's take that as a good omen, shall we? :rofl:
