### ISSUE TITLE
Connectivity status

### ISSUE THREAD

**Issue by hamen** [stealthcopter/AndroidNetworkTools#3]
Hi Matthew,
do you think that the `Ping` utility could be used as connection availability utility? Do you see any downside? Thank you.

**Comment by stealthcopter** [comment]
Hi Hamen,

Yes, it could be used to test for connectivity. The only downside I can think of would be that you need to provide an address that you know will permanently be up (and is responding to pings, some servers do not respond), so you could have a few 'always up' known hosts to ping. Or you could just use the address of a server relevant to your project, in that case, all you really care about is the connectivity to your own end point.

Mat

**Comment by hamen** [comment]
:+1: Thank you
