### ISSUE TITLE
HTC Ping error

### ISSUE THREAD

**Issue by kibrushi** [stealthcopter/AndroidNetworkTools#35]
Dear friend, first of all thanks for this amazing library and sorry for my english.

After many tests with lot off devices i found a problem with **Htc M9**. When i make a ping request it's always return 0 and in PingResult error is always failed.

there are some examples from my logs :   

```
PingResult{ia=speedtest.hyperhosting.gr/31.22.112.100, isReachable=false, error='failed, exit = 1', timeTaken=0.0, fullString='null', result='null'}

PingResult{ia=speedtest.hyperhosting.gr/31.22.112.100, isReachable=false, error='failed, exit = 1', timeTaken=0.0, fullString='null', result='null'}

PingResult{ia=speedtest.gr-ix.gr/62.217.126.171, isReachable=false, error='failed, exit = 1', timeTaken=0.0, fullString='null', result='null'}

PingResult{ia=speedtest.gr-ix.gr/62.217.126.171, isReachable=false, error='failed, exit = 1', timeTaken=0.0, fullString='null', result='null'}

```

So my question is if it's library bug or something going wrong with my code.
Thanks in advance.

**Comment by stealthcopter** [comment]
Can you show the code you are using? I think it's most likely you are trying to use a native ping binary on a phone that doesn't have one.

**Comment by stealthcopter** [comment]
Closing as no response, please reopen if you are still having this problem
