### ISSUE TITLE
Detect Internet connection

### ISSUE THREAD

**Issue by cc1218** [stealthcopter/AndroidNetworkTools#4]
Hi, 
I am using your library to detect whether there is an Internet connection.

On some situations, the Mobile Data is enabled, but my app cannot connect to the Internet, the PingResult returns isReachable=true four fifths probability.

eg: on MIUI ROM, forbidden network through Network Control app.

**Comment by stealthcopter** [comment]
Hello,

Are you saying the Ping class is returning an incorrect result? As it may be that ping is indeed working 4 /5 times but a webpage cannot be loaded. More information please :)

**Comment by stealthcopter** [comment]
Going to close this as no clarification given. Please feel free to open it again if you feel it's needed. Thanks
