### ISSUE TITLE
Set TTL on ping test?

### ISSUE THREAD

**Issue by robross0606** [stealthcopter/AndroidNetworkTools#40]
Is there an option somewhere to set the TTL on ping tests?

**Comment by stealthcopter** [comment]
Not yet, but I will look at adding it into the next version :)

**Comment by robross0606** [comment]
See my pull request.

**Comment by stealthcopter** [comment]
awesome, nice work!

**Comment by stealthcopter** [comment]
Done and I've released 0.4.1 with it in! Thanks for the awesome PR

**Comment by robross0606** [comment]
Awesome.  Thank you for the simple library with a beautiful API.
