### ISSUE TITLE
not able use this in emulator

### ISSUE THREAD

**Issue by nikhilgarg89** [stealthcopter/AndroidNetworkTools#45]
do you know any workaround to make it working on emulator

**Comment by stealthcopter** [comment]
I've tested here and I've got the sample app working fine in an emulator. What was the issue you were having running it?

**Comment by nikhilgarg89** [comment]
i was trying  to ping my system network address and i was not getting the response.

**Comment by stealthcopter** [comment]
This is probably something to do with the networking of the emulator. If you can try in the emulator's shell and check if the system is pingable from there. Something like:

# Connect to emualtor's shell
adb shell

# Ping
ping 192.168.0.3
