### ISSUE TITLE
UI thread blocked when find local devices in subnet

### ISSUE THREAD

**Issue by nambv** [stealthcopter/AndroidNetworkTools#46]
Hi @stealthcopter , when I am using your iib to scan devices inside local network, it blocked the ui thread, make the app not responding. Can you deal with it?

```
SubnetDevices.fromLocalAddress().findDevices(object : SubnetDevices.OnSubnetDeviceFound {
            override fun onDeviceFound(device: Device) {
            }
            override fun onFinished(devicesFound: java.util.ArrayList<Device>) {
            }
```

Looking forward to hearing from you.
Thanks a lot!

**Comment by nambv** [comment]
hi @stealthcopter have you fixed it yet? :D

**Comment by nikhilgarg89** [comment]
@stealthcopter  any fix or workaround for this...

**Comment by nambv** [comment]
it's been a long time ...

**Comment by stealthcopter** [comment]
Sorry guys, had some life stuff get in the way. I will get this fixed today :smiley:

**Comment by nambv** [comment]
@stealthcopter glad to hear it!

**Comment by nambv** [comment]
@stealthcopter thank you very much! 👍

**Comment by nikhilgarg89** [comment]
Still issue is there in 4.2 build

**Comment by stealthcopter** [comment]
@nikhilgarg89 Do you get this in the sample app? I cannot reproduce the issue.

**Comment by nikhilgarg89** [comment]
@stealthcopter  i have not tried in sample app but implemented in my fragment 
SubnetDevices.fromLocalAddress().findDevices(new SubnetDevices.OnSubnetDeviceFound() {
        @Override
        public void onDeviceFound(Device device) {
            // Stub: Found subnet device
        }

        @Override
        public void onFinished(ArrayList<Device> devicesFound) {
            // Stub: Finished scanning
        }
    });

and got ANR..

**Comment by stealthcopter** [comment]
@nikhilgarg89 ah cool, thanks for letting me know :)
