### ISSUE TITLE
ping command timeout and ttl arguments error ?

### ISSUE THREAD

**Issue by asiontang** [stealthcopter/AndroidNetworkTools#48]
in the `PingNative.java` code
>`runtime.exec(pingCommand + " -c 1 -w " + timeoutSeconds + " -w" + ttl + " " + address);`

maybe below is the right code?
>` -W + timeoutSeconds`    
> ` -t" + ttl `

Device Info:
>1. 天天模拟器 Android 4.4.4 
>1. ZUK Z2 Android 7.1.2

Ping command help:
> root@hlteuc:/ # ping
  Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination

**Comment by stealthcopter** [comment]
@asiontang You're completely right, fixing this now! Thanks

**Comment by stealthcopter** [comment]
Fixed in 0.4.3
