### ISSUE TITLE
Redundant tags in library manifest

### ISSUE THREAD

**Issue by SemenovAlexander** [stealthcopter/AndroidNetworkTools#5]
Hi, thanks for great library. 

I've faced issues, while attaching you library:
1/ Support library in my project conflicted with version, added in library and I had to exclude it - you should make support library dependency `provided` instead of `compile`

2/ Manifest  merger fails on allowBackup attribute. Probably, you should remove application tag from library manifest completely.
Error as follows:

```
Error:Execution failed for task ':app:processNormalGoogleTrueDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:27:9-36
  	is also present at [com.github.stealthcopter:AndroidNetworkTools:0.1.2] AndroidManifest.xml:14:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:16:5-34:19 to override.
```

**Comment by stealthcopter** [comment]
Thanks for the tip, I've made the changes and published a new release :)

**Comment by stealthcopter** [comment]
Thanks for the tip, I've made the changes and published a new release :)
