### ISSUE TITLE
Native ping java Process streams not closed

### ISSUE THREAD

**Issue by ravishekhar88** [stealthcopter/AndroidNetworkTools#53]
Hi,

In the PingNative::ping method, the process' input/output/error streams are not closed after completion.

While using this library in Android API level 23 (Marshmallow), it was leading to a spike in number of pipe file descriptors, eventually crashing the user App as the number of FDs were exceeding the allowed limit per process, if GC was not invoked at that instant. However, I did not face the same issue in Android API level 28 (Oreo).

**Comment by Majki94** [comment]
This can be fixed by adding proc.destroy(); at the end of ping method.
It is also good to close reader and buffer.

**Comment by stealthcopter** [comment]
This fix is added into the 0.4.4 build, thanks for your help!
