### ISSUE TITLE
Publish the application on F-Droid

### ISSUE THREAD

**Issue by jonadem** [stealthcopter/AndroidNetworkTools#54]
Be the first network tools application on [F-Droid](https://f-droid.org/) ! ;-)

**Comment by stealthcopter** [comment]
@IzzySoft used to publish it from his website to F-Droid automatically, not sure why it's stopped picking it up. Might want to get in touch with him?

**Comment by IzzySoft** [comment]
@stealthcopter where did I stop? Your last tagged version is 0.4.3 – which can be [found in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.stealthcotper.networktools).

But apart from that, what @jonadem asks for is getting it into the *official* repo. I see nothing speaking against that (except that for auto-updates there, you'd need to put versionName/versionCode *directly* into your `app/build.gradle` (F-Droid cannot deal with variables there).

So if you wish, I could initiate the inclusion procedure (note: I'm meanwhile one of the F-Droid maintainers).

**Comment by stealthcopter** [comment]
Ahhhhhhhh sorry I misunderstood what was happening. Thanks again for hosting your repo :)

I'll have a look at removing the variables and read up more about F-droid

**Comment by IzzySoft** [comment]
If you need any help, ring the bell. As a "quick note": I could open an RFP (Request For Packaging) for your app at F-Droid. Our bot would then scan its Github repo (this one here) and check if everything is OK. If it is (what I assume), one of our "integrators" would see if it can be build. That being successful, your app's Metadata would be merged with ours, and a few days later your app should be available in our catalogue.

No harm trying. Official repo has more prestige (and trust) than mine 😉

For deeper details, may I recommend you the appropriate article from my blog series on F-Droid? [F-Droid for advanced users and developers](https://android.izzysoft.de/articles/named/fdroid-intro-2) explains things in more details. The corresponding chapter for including your app with F-Droid is [this one](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp).

**Comment by IzzySoft** [comment]
@stealthcopter any news on this? Once you've adjusted the gradle and made a new release, we could open a packaging request (RFP) at F-Droid.

**Comment by stealthcopter** [comment]
Next commit contains the build version name/code in the app/build.gradle 
@IzzySoft Please feel free to initiate a RFP for it :)

**Comment by IzzySoft** [comment]
Thanks! Put on my list and hopefully will file it this week (if someone else is faster, just go ahead :rofl:). Currently have to run, work calls :cry:

**Comment by IzzySoft** [comment]
OK, [here you go](https://gitlab.com/fdroid/rfp/issues/1137). You might consider establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) to provide screenshots (and also be able to maintain summary and description yourself, among other things). One place to rule them all: Fastlane Supply also ships to Play Store :wink:

**Comment by stealthcopter** [comment]
@IzzySoft Thanks for this, I've added the fastlane structure and published a new release 0.4.5 let me know if there is anything else I need to do!

**Comment by IzzySoft** [comment]
Thanks @stealthcopter – I hope `en-GB` will do (AFAIK F-Droid always defaults to `en-US` if a language isn't present; maybe a symlink would do but I cannot tell). I left a note in my RFP so the packager(s) make sure to verify. As it's not yet processed, you could of course add something and retag to make sure :wink:

**Comment by stealthcopter** [comment]
@IzzySoft I've replaced it with en-US and pushed a new build out for simplicity

**Comment by IzzySoft** [comment]
Ooops… Houston, now we have a different problem: `versionName` doesn't match the tag name anymore…

**Comment by stealthcopter** [comment]
Whoops, one day I'll get this right! Have pushed a new build 0.4.5.2

**Comment by IzzySoft** [comment]
:laughing: Yeah, now it fits. Updated the RFP accordingly and hope it will be picked up soon. Thanks!

**Comment by beli3ver** [comment]
@IzzySoft is there any news on this?

**Comment by IzzySoft** [comment]
Unfortunately not. Must have been overlooked. I've just pinged our packagers, in the hope to motivate one. Be welcome to ping there yourself should noone answer and nothing happen for another week or two.

**Comment by stealthcopter** [comment]
@IzzySoft of course :) thanks for all your help with this!

**Comment by IzzySoft** [comment]
Gladly, @stealthcopter – and I will miss it in my repo. Was there for 2.5 years now…
