### ISSUE TITLE
Mac address is always null

### ISSUE THREAD

**Issue by retrostar94** [stealthcopter/AndroidNetworkTools#59]
Whenever i scan or try to find the mac address it always returns null

**Comment by stealthcopter** [comment]
Can you provide your calling code so I can run some tests on it? The local device's mac address will be hidden as it is a security feature in android.

**Comment by dev4mobile** [comment]
android 10 can't fetch subnet devices mac address?

**Comment by dev4mobile** [comment]
![43921577245623_ pic](https://user-images.githubusercontent.com/6851386/71431362-50fbee00-270c-11ea-865c-2c8d2bff35ab.jpg)

**Comment by maxto024** [comment]
@dev4mobile  did you find solution i have same issue

**Comment by Kushagrasaxena-13** [comment]
I want to work on this bug !!!

**Comment by Kushagrasaxena-13** [comment]
Hey sir please see my update . I have resolved the bug

**Comment by Kushagrasaxena-13** [comment]
@stealthcopter please see it

**Comment by TayStyles-AAP** [comment]
@Kushagrasaxena-13 did you get this working? would love to finally be able to use this library in my latest build but mac is always null!

**Comment by huangyanxiong01** [comment]
@TaylorStyles did you find solution i have same issue

**Comment by stealthcopter** [comment]
This happens because Android hides local network MAC addresses for privacy reasons. There are some work arounds but nothing with the latest versions of Android :(
