### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [stealthcopter/AndroidNetworkTools#60]
Hi @stealthcopter – I'm just wondering, with the last commit being from 8/2018 and issues are left unanswered: are you still maintaining this project? Not complaining, just informal asking :wink: If you "gave up" on it, it would be good to have a clear statement on the fact (best "on the front-page", i.e. in the Readme) and maybe have the repo archived (which can be undone any time).

Thanks!

**Comment by stealthcopter** [comment]
Hey @IzzySoft - no problem, thanks for asking. I'm not giving up on maintaining it just yet! But other priorities mean I don't have as much time as I'd like to focus on this. I would like to do a re-write in kotlin at some point if I find myself with excess time. I'll have quick look over the issues and fix the low-hanging fruit.

**Comment by IzzySoft** [comment]
Grat to read, thanks! Looking forward to that. If you'd just ping me when a new release is ready, that'd be great! All the best!

**Comment by IzzySoft** [comment]
Thanks for the revival! :green_heart:
