### ISSUE TITLE
Android 10 and access to /proc/net/*

### ISSUE THREAD

**Issue by Zaporozhec7** [stealthcopter/AndroidNetworkTools#64]
> On devices that run Android 10 or higher, apps cannot access /proc/net 
https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem 

So seems this library will not work on Android 10, in part of that use "/proc/net/arp" read.

As workaround, possibly command "ip neigh show" can be used, that should be still available in Android 10. Althought I have not checked that.

**Comment by stealthcopter** [comment]
@Zaporozhec7 Thanks for the info! You're right, on Android 10 the features in ARPInfo class will return empty results. I will look at adding in the data from `ip neigh show` into the next release

**Comment by stealthcopter** [comment]
Merged in PR https://github.com/stealthcopter/AndroidNetworkTools/pull/66
