### ISSUE TITLE
Attach APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [stealthcopter/AndroidNetworkTools#7]
Would you mind attaching the corresponding `.apk` file to each release on the `releases/` page – for folks who cannot or do not want to use Playstore? Thanks in advance!

**Comment by stealthcopter** [comment]
The application is just an example of what the library I've written is capable of. I'm not sure publishing the apk would be that useful as the app isn't very useful in itself. I'd recommend checking out PortDroid which is a more complete network analysis application which I have written using this library. 

Out of interest what app store do you use?

**Comment by IzzySoft** [comment]
I've just found it on my daily GH-Analysis today, and added it [here](https://android.izzysoft.de/applists/category/named/network_admin_info#group_383) and [here](https://android.izzysoft.de/applists/category/named/network_admin_sniffspoof#group_391). It's decently sized, permission friendly (the only IP-Toolbox there just requesting the single required permission, in fact). So I was considering to also add it [here](https://android.izzysoft.de/repo) – for other folks like me who take privacy serious and avoid Playstore whenever possible :)

PortDroid is already at the second location, but I couldn't find it at Github nor F-Droid. Moreover, it's 10 times more permission-hungry. And its description lacks information on what for it needs to know my location or access my storage :see_no_evil:

I mainly use F-Droid, with its main repo plus the microG repo and mine. If I really need something from Play, I mostly take Raccoon to pick the `.apk`. But that would mean no automatic updates then, of course.

**Comment by stealthcopter** [comment]
If you take privacy that seriously, you should probably not be installing apk files from the internet as they are more likely to be malicious than those found in app stores. I recommend building from source is the best method of ensuring that there is no malicious code in the apks that you install.

But I will have a look to see if the continuous integration system I use can automatically upload apk's to my github releases. If it can do this without too much hassle then I will add it in :)

**Comment by IzzySoft** [comment]
@stealthcopter Yes, I take privacy seriously. And of course I'm aware of other risks, which is why I do not use just "any APK found on the net", plus also run the downloads through a bunch of scanners. I take all the precautions known to me – and I don't like Google snooping on my every data with those strange  "we owe you" so-called "privacy rules" `</rant>™` :stuck_out_tongue_winking_eye: There is no such thing as 100% security, but I do what I can.

So earnest thanks for considering this! I'll stand to my above offer once the APK is there :innocent:

**Comment by stealthcopter** [comment]
@IzzySoft I've just pushed a new update and attached the latest apk to the release
`https://github.com/stealthcopter/AndroidNetworkTools/releases/tag/0.2.0`

**Comment by IzzySoft** [comment]
Thanks! Just added it to my repo now, as promised (find it [here](https://apt.izzysoft.de/fdroid/index/apk/com.stealthcotper.networktools) – where you also can see it passed my little malware tests and library checks). Note: The APK itself says it's v0.1.08:

    package: name='com.stealthcotper.networktools' versionCode='6' versionName='0.1.08' platformBuildVersionName=''

If you fix that, please don't forget to 1) do that for future versions as well and 2) also increase the `versionCode` :smile_cat:

**Comment by stealthcopter** [comment]
@IzzySoft Cool thanks. I like the malware checks, good work. The version number isn't currently aligned between the apk and the library itself, this is sloppy on my behalf and will be fixed when I do the next release.

**Comment by IzzySoft** [comment]
If not, the corresponding update run on my end will break with "duplicate versions", and I'll have to fix that manually :scream_cat:

Glad you like the checks! Some basic protection, best as I can do. I'd really like to identify "intrusive libraries" by their names to point them out if found, but unfortunately I never found an API for that…

**Comment by IzzySoft** [comment]
@stealthcopter the latest release again has no `.apk` attached. Just forgotten, or not relevant?

**Comment by stealthcopter** [comment]
@IzzySoft Hello, Sorry for the silence, I didn't see this. I've made some changes I think you'll be pleased about:
1. I've aligned the library and sample app version names/codes
2. I've added automatic APK uploading to github as part of my continuous integration setup so all future releases will have an APK :tada:

Thanks for helping me get this sorted!

**Comment by IzzySoft** [comment]
Thanks a lot! I see the attachment was already placed yesterday, so my updater has already picked it.

Oh, and besides: library check is in place for a while now as well on my repo, with some "intrusive candidates" being pointed out (bolded, monitor-icon linked to a closer description). Not perfect, but better than nothing :wink:

**Comment by stealthcopter** [comment]
Awesome, thanks :) Looks like I'm all good on the library front

**Comment by IzzySoft** [comment]
Yupp – unless my scanner missed something :wink: Congrats!
