### ISSUE TITLE
How to I get round trip times in milli-seconds?

### ISSUE THREAD

**Issue by Reegan01** [stealthcopter/AndroidNetworkTools#9]
Hi friend,  You are done awesome job. 

I want a info from you. How to get round trip times Minimum, Maximum and Average in milli-seconds

**Comment by stealthcopter** [comment]
Currently this isn't implemented in the library but you can easily modify how you call the library to achieve this as follows:

```
    // Perform an asynchronous ping
    Ping.onAddress(ipAddress).setTimeOutMillis(1000).setTimes(5).doPing(new Ping.PingListener() {

      long noPings = 0;
      long totalPingTimeMillis = 0;
      long minPingTimeMillis = -1;
      long maxPingTimeMillis = -1;

      @Override
      public void onResult(PingResult pingResult) {

        if (!pingResult.hasError()){

          long timeTakenMillis = (long) (pingResult.getTimeTaken() * 1000);

          if (maxPingTimeMillis == - 1 || timeTakenMillis > maxPingTimeMillis) maxPingTimeMillis = timeTakenMillis;
          if (minPingTimeMillis == - 1 || timeTakenMillis < minPingTimeMillis) minPingTimeMillis = timeTakenMillis;

          totalPingTimeMillis += timeTakenMillis;
        }

      }

      @Override
      public void onFinished() {

        long averageTimeMillis = totalPingTimeMillis / noPings;
        // minPingTimeMillis;
        // maxPingTimeMillis;
      }
    });
```

In the next release I will add these ping statistics to the onFinished call

**Comment by Reegan01** [comment]
Thanks a lot for your immediate awesome response and it's working correctly.

And sorry for this disturb, I have another one request  : 
Can I able to calculate Lost Packets in percentage?
Send and Received packets are I can get from `.setTimes(5)` method. 5 is may send and received packets. But calculate lost packets?

**Comment by stealthcopter** [comment]
From the above example you'd just keep track the number of times the ping has an error. If we use the same code from the example above it would become:

```
// Perform an asynchronous ping
Ping.onAddress(ipAddress).setTimeOutMillis(1000).setTimes(5).doPing(new Ping.PingListener() {

  long noPings = 0;
  long noLostPackets = 0;
  long totalPingTimeMillis = 0;
  long minPingTimeMillis = -1;
  long maxPingTimeMillis = -1;

  @Override
  public void onResult(PingResult pingResult) {

    noPings++;

    if (!pingResult.hasError()){

      long timeTakenMillis = (long) (pingResult.getTimeTaken() * 1000);

      if (maxPingTimeMillis == - 1 || timeTakenMillis > maxPingTimeMillis) maxPingTimeMillis = timeTakenMillis;
      if (minPingTimeMillis == - 1 || timeTakenMillis < minPingTimeMillis) minPingTimeMillis = timeTakenMillis;

      totalPingTimeMillis += timeTakenMillis;
    }
    else{
      noLostPackets++;
    }

  }

  @Override
  public void onFinished() {

    long averageTimeMillis = totalPingTimeMillis / noPings;
    // minPingTimeMillis;
    // maxPingTimeMillis;
    // noLostPackets;
   // Example calculation of packet loss in percent
    float packetLossPercent = (100.0 * noLostPackets ) / noPings
  }
});

```

Note that it keeps track of the number of pings inside the PingListener rather than just using the value set in setTimes(..). This is in case you call cancel while the ping command is running and onFinished is called before achieving the number of pings requested.

Thanks

**Comment by Reegan01** [comment]
I tried to convert long values to two digit milliseconds But it not working. I tried many ways to get two digit like 23.34 ms. please help me to convert this.

`long minPingTimeMillis;
  long maxPingTimeMillis;`

`String.format("%.2f ms",minPingTimeMillis)`

**Comment by stealthcopter** [comment]
A `long` doesn't have any decimal places, which is probably why you are struggling. 

`String.format("%d ms",minPingTimeMillis)`

If you want decimal places, I'd suggest using a double instead.

**Comment by Reegan01** [comment]
sorry for this late thanks,  And I never forgot your immediate response of my questions. Thanks and God Bless

**Comment by Alamusitl** [comment]
tks
