### ISSUE TITLE
ip neigh command does not work after upgrading targetSDK to 30

### ISSUE THREAD

**Issue by 5hahryar** [stealthcopter/AndroidNetworkTools#91]
Reading the ARP table and accessing the MAC address of devices on network is working just fine. But when you upgrade the targetSDK to 30, suddenly the "ip neigh" command won't return a value anymore. 
I'm guessing this has something to do with the restrictions on android. Is there any way to fix this issue?
Note: tested on samsung galaxy s10 running android 11.

**Comment by fulvius31** [comment]
Hello, I did a library to fix that!
https://github.com/fulvius31/ip-neigh-sdk30

**Comment by Agmcz** [comment]
> Hello, I did a library to fix that! https://github.com/fulvius31/ip-neigh-sdk30

Hello
I used the library and it works fine on Android 12,
but when using infinite loop there is a crash!!!
`while (true) {
    Toast.makeText(MainActivity.this, ArpNDK.getARP(), Toast.LENGTH_SHORT).show();
 }`
Please fix it.
